import { CommunityDiscussion } from '../types';

export const LATEX_EXAMPLE_DOC: CommunityDiscussion = {
  id: 'system-doc-002',
  lectureId: 'math-reference',
  channelId: 'system',
  userId: 'system',
  userName: 'Math Professor',
  transcript: [],
  createdAt: 1766020000000,
  isManual: true,
  title: "LaTeX & Mathematical Notation Guide",
  designDoc: `
# LaTeX Mathematical Reference

This document demonstrates the mathematical typesetting capabilities of the AIVoiceCast Platform using KaTeX.

## 1. Inline Math
You can include math within a sentence using single dollar signs. For example, the Pythagorean theorem is $a^2 + b^2 = c^2$. You can also show variables like $\\alpha$, $\\beta$, and $\\gamma$.

## 2. Block Math
For larger equations, use double dollar signs:

$$
e^{i\\pi} + 1 = 0
$$

## 3. Calculus
The definition of a derivative:
$$
f'(a) = \\lim_{h \\to 0} \\frac{f(a+h) - f(a)}{h}
$$

And a complex integral:
$$
\\int_{-\\infty}^{\\infty} e^{-x^2} dx = \\sqrt{\\pi}
$$

## 4. Linear Algebra
Matrices are also supported:

$$
\\begin{pmatrix}
1 & 0 & 0 \\\\
0 & 1 & 0 \\\\
0 & 0 & 1
\\end{pmatrix}
$$

## 5. Statistics
The standard normal distribution probability density function:
$$
\\phi(x) = \\frac{1}{\\sigma\\sqrt{2\\pi}} e^{-\\frac{1}{2}\\left(\\frac{x-\\mu}{\\sigma}\\right)^2}
$$

## 6. Physics
Einstein's Field Equations:
$$
G_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\kappa T_{\\mu\\nu}
$$

---
*Generated by AIVoiceCast Math Engine*
`
};

export const APP_COMPARISON_DOC: CommunityDiscussion = {
  id: 'system-doc-001',
  lectureId: 'system-architecture',
  channelId: 'system',
  userId: 'system',
  userName: 'System Architect',
  transcript: [],
  createdAt: 1766016000000,
  isManual: true,
  title: "Design Doc: Document Studio vs. Community Blog",
  designDoc: `
# Design Specification: Knowledge Pillars

**Status:** Draft | **Author:** Engineering Team | **Date:** Dec 18, 2025

## 1. Executive Summary
The AIVoiceCast platform bifurcates long-form content into two distinct engines: the **Document Studio** and the **Community Blog**. This document outlines the technical and philosophical differences between these two modules.

## 2. Comparison Matrix

| Feature | Document Studio | Community Blog |
| :--- | :--- | :--- |
| **Primary Intent** | Knowledge capture & technical archiving | Social storytelling & public updates |
| **Input Source** | Live Transcripts, AI Analysis, Design notes | Human-authored articles & opinion pieces |
| **Default Privacy** | Private / Restricted (Team Access) | Public (Community Feed) |
| **Structure** | Technical Markdown, Tables, Code Blocks | Narrative Prose, Media embeds, Excerpts |
| **Output Formats** | **Google Docs**, PDF, JSZip Package | Web Feed, Social Share, Comments |
| **AI Role** | Synthesizes transcripts into Design Docs | Suggests titles, tags, and proofreads |

## 3. Architectural Flow
The following diagram demonstrates the synchronization process between the frontend, the Gemini AI engine, and our dual-storage persistence layers.

\`\`\`plantuml
@startuml
skinparam backgroundColor #0f172a
skinparam sequence {
    ArrowColor #818cf8
    LifeLineBorderColor #818cf8
    ParticipantBorderColor #334155
    ParticipantBackgroundColor #1e293b
    ParticipantFontColor #f8fafc
}

participant "User Browser" as UI
participant "Gemini 3 Pro" as AI
database "IndexedDB (Cache)" as Cache
database "Cloud Firestore" as DB

UI -> AI: Send Session Context
AI --> UI: Synthesized Technical Draft
UI -> Cache: Cache Result (Offline Access)
UI -> DB: Persist Document (Collaboration)
UI -> UI: Render Preview
@enduml
\`\`\`

## 4. Mathematical Modeling
We model the efficiency of our AI-driven synthesis using the context compression ratio $R$. For a session with $n$ individual transcript turns, the document fidelity $F$ is defined as:

$$
F = \\int_{0}^{T} \\frac{\\sum_{i=1}^{n} w_i \\cdot \\text{entropy}(turn_i)}{\\text{tokens}_{total}} dt
$$

Where $w_i$ represents the semantic weight assigned by the reasoning engine. Inline math examples like $\\sigma^2$ or $\\sqrt{x}$ are also supported for technical specifications.

## 5. Behavioral Architecture

### The Document Studio (Workflow Engine)
The Studio is designed for "Work-in-Progress" and "Institutional Memory." 
- **The Lifecycle:** A Live Session (Audio) → Transcription → **AI Analysis** → Design Document.
- **Integration:** Deeply linked to **Google Drive**. It allows users to export a synthesized meeting summary directly into their professional workspace as a formal Google Doc.

### The Community Blog (Social Engine)
The Blog is designed for "Audience Reach" and "Community Engagement."
- **The Lifecycle:** Concept → Editor Draft → Peer Review (Optional) → **Published to Feed**.
- **Engagement:** Focuses on Likes, Comments, and Follower growth. It is the "Social Identity" of a creator.

## 6. Conclusion
Use the **Document Studio** when you are building and need to remember *how* or *why*. Use the **Blog** when you have something to say to the *world*.
`
};